/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacmangame.view;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import pacmangame.Controller.LoginController;
import Media.Media;
import Media.EImage;
import GUI.PostLoginMainMenu;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class LoginView extends javax.swing.JFrame {

    // Add missing fields for password visibility button
    private javax.swing.JLabel showPasswordBtn;
    // Add controller field
    private LoginController loginController;
   
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        
        // Set the background color to sky blue
        getContentPane().setBackground(new Color(135, 206, 235));
        
        // Set window size to 1000x600 and center it on screen
        setSize(1000, 600);
        
        setLocationRelativeTo(null);
        
        // Set transparent backgrounds
        usernametextfield.setBackground(new Color(0,0,0,0));
        passwordtextfield.setBackground(new Color(0,0,0,0));
        
        // Set password field
        passwordtextfield.setEchoChar('\u0000');  // Initially show placeholder
        
        // Setup show/hide password functionality
        setupPasswordVisibility();
        
        // Setup login button action
        setupLoginButton();
        
        // Initialize controller
        loginController = new LoginController();
        
        // Set frame icon
        setIconImage(Media.getImg(EImage.logo));
        
        // Make the frame visible
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        loginTitle = new javax.swing.JLabel();
        usernametextfield = new javax.swing.JTextField();
        passwordtextfield = new javax.swing.JPasswordField();
        userimg = new javax.swing.JLabel();
        passwordimg = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        createAccountButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();

        // Title
        loginTitle.setFont(new java.awt.Font("Times New Roman", 1, 36));
        loginTitle.setText("Login");
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(30, 0, 40, 0);
        gbc.anchor = GridBagConstraints.CENTER;
        getContentPane().add(loginTitle, gbc);

        gbc.gridwidth = 1;
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.EAST;

        // Username row
        userimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/img/profile-user (1) (1).png")));
        gbc.gridx = 0;
        gbc.gridy = 1;
        getContentPane().add(userimg, gbc);

        usernametextfield.setText("Enter Your username");
        usernametextfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(30, 144, 255)));
        usernametextfield.setPreferredSize(new java.awt.Dimension(250, 32));
        usernametextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) { usernamefocus(evt); }
            public void focusLost(java.awt.event.FocusEvent evt) { usernamefocuslost(evt); }
        });
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.CENTER;
        getContentPane().add(usernametextfield, gbc);
        // No eye icon for username

        // Password row
        passwordimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepicker/img/lock (1) (1).png")));
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        getContentPane().add(passwordimg, gbc);

        passwordtextfield.setText("Enter your password");
        passwordtextfield.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(30, 144, 255)));
        passwordtextfield.setPreferredSize(new java.awt.Dimension(250, 32));
        passwordtextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) { passwordfocus(evt); }
            public void focusLost(java.awt.event.FocusEvent evt) { passwordfocuslost(evt); }
        });
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.CENTER;
        getContentPane().add(passwordtextfield, gbc);

        // Eye button for password
        showPasswordBtn = new javax.swing.JLabel();
        showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/show (1).png")));
        showPasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPasswordBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        showPasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (passwordtextfield.getEchoChar() == '•') {
                    passwordtextfield.setEchoChar('\u0000');
                    showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/hide (1).png")));
                } else {
                    String password = new String(passwordtextfield.getPassword());
                    if (!password.equals("Enter your password")) {
                        passwordtextfield.setEchoChar('•');
                    }
                    showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/show (1).png")));
                }
            }
        });
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        getContentPane().add(showPasswordBtn, gbc);

        // Login button
        loginButton.setFont(new java.awt.Font("Times New Roman", 1, 24));
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { hover(evt); }
            public void mouseExited(java.awt.event.MouseEvent evt) { hoverlost(evt); }
        });
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(40, 0, 10, 0);
        gbc.anchor = GridBagConstraints.CENTER;
        getContentPane().add(loginButton, gbc);
        gbc.gridwidth = 1;
        gbc.insets = new Insets(10, 10, 10, 10);

        // Bottom text
        JPanel bottomPanel = new JPanel();
        bottomPanel.setBackground(new Color(135, 206, 235));
        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16));
        jLabel2.setText("Don't Have an Account ? ");
        createAccountButton.setFont(new java.awt.Font("Segoe UI", 1, 16));
        createAccountButton.setForeground(new java.awt.Color(51, 51, 255));
        createAccountButton.setText("Create Account");
        createAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) { createAccount_click(evt); }
        });
        bottomPanel.add(jLabel2);
        bottomPanel.add(createAccountButton);
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(20, 0, 10, 0);
        gbc.anchor = GridBagConstraints.CENTER;
        getContentPane().add(bottomPanel, gbc);

        pack();
    }

    private void usernamefocus(java.awt.event.FocusEvent evt) {
        if (usernametextfield.getText().equals("Enter Your username")) {
            usernametextfield.setText("");
            usernametextfield.setForeground(Color.black);
        }
    }

    private void usernamefocuslost(java.awt.event.FocusEvent evt) {
        if (usernametextfield.getText().isEmpty()){
            usernametextfield.setText("Enter Your username");
            usernametextfield.setForeground(Color.black);
        }
    }

    private void passwordfocus(java.awt.event.FocusEvent evt) {
        String password = new String(passwordtextfield.getPassword());
        if (password.equals("Enter your password")) {
            passwordtextfield.setText("");
            passwordtextfield.setEchoChar('•');
            passwordtextfield.setForeground(Color.black);
            showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/show (1).png")));
        }
    }

    private void passwordfocuslost(java.awt.event.FocusEvent evt) {
        String password = new String(passwordtextfield.getPassword());
        if (password.isEmpty()) {
            passwordtextfield.setEchoChar('\u0000');
            passwordtextfield.setText("Enter your password");
            passwordtextfield.setForeground(Color.black);
            showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/show (1).png")));
        }
    }

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        handleLoginButtonClick();
    }

    private void hover(java.awt.event.MouseEvent evt) {
        loginButton.setBackground(new java.awt.Color(70, 130, 180));
        loginButton.setForeground(Color.WHITE);
        
    }

    private void hoverlost(java.awt.event.MouseEvent evt) {
        loginButton.setBackground(new java.awt.Color(255, 255, 0));
        loginButton.setForeground(Color.BLACK);
    }

    private void createAccount_click(java.awt.event.MouseEvent evt) {
        this.dispose();
        new RegistrationView().setVisible(true);
    }

    private void setupPasswordVisibility() {
        showPasswordBtn = new javax.swing.JLabel();
        showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/show (1).png")));
        showPasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPasswordBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        showPasswordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                togglePasswordVisibility();
            }
        });
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.LINE_START;
        gbc.insets = new Insets(0, 5, 0, 0);
        getContentPane().add(showPasswordBtn, gbc);
    }
    
    private void togglePasswordVisibility() {
        if (passwordtextfield.getEchoChar() == '•') {
            passwordtextfield.setEchoChar('\u0000');
            showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/hide (1).png")));
        } else {
            String password = new String(passwordtextfield.getPassword());
            if (!password.equals("Enter your password")) {
                passwordtextfield.setEchoChar('•');
            }
            showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/show (1).png")));
        }
    }
    
    private void setupLoginButton() {
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleLoginButtonClick();
            }
        });
    }

    private void handleLoginButtonClick() {
        String username = usernametextfield.getText();
        String password = new String(passwordtextfield.getPassword());

        if (username.equals("Enter Your username") || password.equals("Enter your password")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please enter both username and password.", 
                "Login Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean loginSuccess = loginController.loginUser(username, password);

        if (loginSuccess) {
            this.dispose();
            new PostLoginMainMenu(loginController.getLoggedInUser());
        } else {
            clearForm();
        }
    }

    private void clearForm() {
        usernametextfield.setText("Enter Your username");
        usernametextfield.setForeground(Color.black);

        passwordtextfield.setEchoChar('\u0000');
        passwordtextfield.setText("Enter your password");
        passwordtextfield.setForeground(Color.black);
        showPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("imagepicker/img/show (1).png")));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    
    private javax.swing.JLabel createAccountButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel passwordimg;
    private javax.swing.JPasswordField passwordtextfield;
    private javax.swing.JLabel userimg;
    private javax.swing.JTextField usernametextfield;
    
}